theme: jekyll-theme-slate
title: Welcome to the Rye4Ray’s homepage!
description: Feel free to bookmark this to keep an eye on my project updates

# Site navigation links
- title: Home
  url: /
  
- title: About Me
  url: /about/
  
- title: Portfolio
  url: /portfolio/
